FROM python:3.13-bookworm

ENV APT_DEPS \
    iputils-ping \
    docker.io

ENV PIP_DEPS \
    ansible \
    ansible-lint

RUN apt-get update && apt-get install -y ${APT_DEPS}

RUN pip install ${PIP_DEPS}

WORKDIR /usr/src/app